"""Regenerates nova_agent/knowledge/tier2_enrichment.json (Round M).

PROVENANCE: the feature lists below were written by the engineering agent from widely taught
textbook clinical knowledge for ~80 high-value Tier-2 diagnoses (common ED/primary-care and
can't-miss conditions). They are NOT clinician-reviewed, NOT derived from a named dataset, make no
diagnostic claim, and fill only typical_features / confirmatory_findings; risk factors, specific
features, contradictions and minimum workup are intentionally left empty (no reliable source).
Run from the repository root:  python scripts/build_tier2_enrichment.py
"""
import json
E = {
 # id: [typical features]
 "cholecystitis": ["right upper quadrant pain", "pain after fatty meals", "fever", "nausea and vomiting", "pain radiating to right shoulder", "tender right upper abdomen on breathing in"],
 "cholangitis": ["right upper quadrant pain", "fever and chills", "jaundice", "dark urine", "confusion in severe cases", "history of gallstones"],
 "biliary_colic": ["episodic right upper abdominal pain", "pain after eating fatty food", "nausea", "pain lasting hours then easing", "pain radiating to back or shoulder blade"],
 "choledocholithiasis": ["right upper quadrant pain", "jaundice", "pale stools", "dark urine", "history of gallstones"],
 "bowel_obstruction": ["colicky abdominal pain", "repeated vomiting", "abdominal distension", "unable to pass gas or stool", "previous abdominal surgery", "high-pitched bowel sounds"],
 "large_bowel_obstruction": ["abdominal distension", "constipation with no gas passed", "crampy lower abdominal pain", "vomiting late", "history of bowel cancer or volvulus"],
 "diverticulitis": ["left lower quadrant pain", "fever", "change in bowel habit", "constipation or diarrhea", "nausea", "tender left lower abdomen"],
 "mesenteric_ischemia": ["severe abdominal pain out of proportion to examination", "pain after eating", "atrial fibrillation or vascular disease", "vomiting", "bloody stool late", "older age"],
 "peptic_ulcer_disease": ["burning upper abdominal pain", "pain relieved or worsened by eating", "night time pain", "bloating", "NSAID use", "Helicobacter pylori infection"],
 "gi_duodenal_ulcer": ["burning upper abdominal pain", "pain relieved by eating", "night time pain waking from sleep", "NSAID use"],
 "gi_perforated_ulcer": ["sudden severe upper abdominal pain", "rigid abdomen", "pain spreading across abdomen", "history of ulcer or NSAID use", "fever and rapid pulse"],
 "perforated_viscus": ["sudden severe abdominal pain", "rigid board-like abdomen", "rebound tenderness", "lying still", "free air under diaphragm"],
 "gi_peritonitis_gi": ["severe diffuse abdominal pain", "rigid abdomen", "rebound tenderness", "fever", "pain worse with movement"],
 "gi_liver_abscess": ["fever and chills", "right upper quadrant pain", "malaise", "weight loss", "recent abdominal infection"],
 "acute_hepatitis": ["jaundice", "dark urine", "fatigue", "nausea and loss of appetite", "right upper quadrant discomfort", "pale stools"],
 "toxic_megacolon": ["bloody diarrhea", "abdominal distension", "fever", "rapid heart rate", "history of ulcerative colitis or Crohn disease"],
 "ulcerative_colitis": ["bloody diarrhea", "urgency to defecate", "crampy lower abdominal pain", "mucus in stool", "weight loss"],
 "crohn_disease": ["chronic diarrhea", "right lower abdominal pain", "weight loss", "mouth ulcers", "perianal disease"],
 "esophageal_varices": ["vomiting blood", "black tarry stools", "history of cirrhosis or alcohol use", "large volume bleeding", "dizziness on standing"],
 "mallory_weiss_tear": ["vomiting blood after retching", "forceful vomiting", "alcohol binge", "upper abdominal pain"],
 "pericarditis": ["sharp chest pain", "pain eased by leaning forward", "pain worse lying flat or breathing in", "recent viral illness", "fever", "friction rub"],
 "myocarditis": ["chest pain", "palpitations", "recent viral illness", "shortness of breath", "fatigue", "raised troponin"],
 "cardiac_tamponade": ["shortness of breath", "low blood pressure", "distended neck veins", "muffled heart sounds", "rapid heart rate", "recent chest trauma or pericarditis"],
 "infective_endocarditis": ["fever", "new heart murmur", "night sweats", "intravenous drug use", "splinter hemorrhages", "prosthetic valve"],
 "deep_vein_thrombosis": ["unilateral calf swelling", "calf pain or tenderness", "warmth and redness of leg", "recent immobility or long travel", "recent surgery", "previous clot"],
 "hypertrophic_cardiomyopathy": ["exertional syncope", "chest pain on exertion", "family history of sudden death", "palpitations", "shortness of breath on exertion"],
 "supraventricular_tachycardia": ["sudden onset rapid regular palpitations", "sudden stop of palpitations", "lightheadedness", "chest discomfort", "episodes lasting minutes"],
 "ventricular_tachycardia": ["palpitations", "syncope", "chest pain", "history of heart attack or cardiomyopathy", "low blood pressure"],
 "atrial_flutter": ["regular rapid palpitations", "shortness of breath", "fatigue", "heart rate near 150"],
 "heart_failure_acute": ["worsening shortness of breath", "unable to lie flat", "leg swelling", "weight gain", "waking breathless at night", "crackles in lungs"],
 "chronic_heart_failure": ["shortness of breath on exertion", "ankle swelling", "fatigue", "needing extra pillows", "weight gain"],
 "hypertensive_emergency": ["severe headache", "blood pressure above 180 over 120", "blurred vision", "chest pain", "confusion", "shortness of breath"],
 "aortic_stenosis": ["exertional chest pain", "exertional syncope", "shortness of breath on exertion", "ejection systolic murmur", "older age"],
 "pheochromocytoma": ["episodic severe headache", "sweating", "palpitations", "episodic high blood pressure", "pallor", "anxiety"],
 "stable_angina": ["chest pressure on exertion", "relieved by rest", "radiation to arm or jaw", "predictable pattern", "risk factors for heart disease"],
 "hyperthyroidism": ["weight loss despite good appetite", "palpitations", "heat intolerance", "tremor", "sweating", "anxiety", "diarrhea", "goiter"],
 "thyroid_storm": ["high fever", "rapid heart rate", "agitation or confusion", "tremor", "known hyperthyroidism", "vomiting and diarrhea"],
 "myxedema_coma": ["low body temperature", "confusion or drowsiness", "slow heart rate", "known hypothyroidism", "cold intolerance", "swelling of face"],
 "adrenal_crisis": ["severe weakness", "low blood pressure", "vomiting and abdominal pain", "long-term steroid use stopped suddenly", "confusion", "low sodium"],
 "addison_disease": ["fatigue", "weight loss", "darkened skin", "salt craving", "low blood pressure", "nausea"],
 "hyperosmolar_hyperglycemic": ["very high blood glucose", "extreme thirst", "frequent urination", "confusion or drowsiness", "dehydration", "older adult with type 2 diabetes"],
 "hypercalcemia": ["excessive thirst", "frequent urination", "constipation", "abdominal pain", "confusion", "bone pain", "history of cancer or hyperparathyroidism"],
 "hypocalcemia": ["tingling around mouth and fingers", "muscle cramps", "carpopedal spasm", "seizure", "recent thyroid or parathyroid surgery"],
 "siadh": ["low sodium", "confusion", "headache", "nausea", "seizure", "concentrated urine"],
 "pituitary_apoplexy": ["sudden severe headache", "visual loss or double vision", "known pituitary tumor", "vomiting", "low blood pressure"],
 "rhabdomyolysis": ["severe muscle pain", "dark cola colored urine", "muscle weakness", "recent intense exercise or crush injury", "statin use", "markedly raised creatine kinase"],
 "epididymitis": ["scrotal pain and swelling", "gradual onset testicular pain", "burning urination", "fever", "relief on lifting the testis", "urethral discharge"],
 "gu_epididymo_orchitis": ["scrotal pain and swelling", "fever", "burning urination", "tender swollen testis", "urethral discharge"],
 "testicular_torsion": ["sudden severe testicular pain", "nausea and vomiting", "high riding testis", "swollen tender testis", "absent cremasteric reflex", "adolescent male"],
 "ovarian_torsion": ["sudden severe lower abdominal pain on one side", "nausea and vomiting", "pelvic mass or cyst", "intermittent colicky pain", "history of ovarian cyst"],
 "pelvic_inflammatory_disease": ["lower abdominal pain", "abnormal vaginal discharge", "fever", "pain with intercourse", "cervical motion tenderness", "new sexual partner"],
 "ruptured_ovarian_cyst": ["sudden lower abdominal pain on one side", "pain during or after exercise or intercourse", "pelvic tenderness", "negative pregnancy test"],
 "prostatitis": ["fever and chills", "pain between scrotum and anus", "burning urination", "frequent urination", "tender boggy prostate"],
 "urinary_retention": ["unable to pass urine", "lower abdominal fullness", "suprapubic pain", "enlarged prostate", "dribbling"],
 "acute_kidney_injury": ["reduced urine output", "rising creatinine", "swelling", "recent vomiting or diarrhea or nephrotoxic drug", "fatigue"],
 "cellulitis_derm": ["red warm swollen skin", "spreading redness", "tender skin", "fever", "skin break or wound", "leg most common"],
 "erysipelas": ["sharply demarcated red raised skin", "fever", "facial or leg involvement", "tender hot skin", "abrupt onset"],
 "der_cutaneous_abscess": ["painful fluctuant lump", "red warm swelling", "pus drainage", "fever"],
 "stevens_johnson_syndrome": ["painful blistering rash", "mouth and eye sores", "fever", "recent new drug", "skin peeling"],
 "angioedema": ["swelling of lips tongue or face", "sudden onset", "difficulty swallowing or breathing", "ACE inhibitor use", "no itching"],
 "sym_hemoptysis": ["coughing up blood", "cough", "shortness of breath", "chest pain", "weight loss", "smoking history"],
 "sym_syncope": ["transient loss of consciousness", "rapid recovery", "lightheadedness before", "palpitations", "injury from fall"],
 "sym_seizure_symptom": ["convulsions", "loss of consciousness", "tongue biting", "incontinence", "post-ictal confusion"],
 "heat_stroke": ["body temperature above 40 degrees", "confusion", "hot dry skin or profuse sweating", "recent heat or exertion", "collapse"],
 "hypothermia": ["body temperature below 35 degrees", "shivering", "confusion", "slow heart rate", "cold exposure"],
 "sickle_cell_disease": ["severe bone pain crisis", "anemia", "jaundice", "history of sickle cell", "chest pain", "recurrent infections"],
 "hereditary_angioedema": ["recurrent swelling without itching", "abdominal pain attacks", "family history", "swelling of airway", "no response to antihistamines"],
 "epistaxis": ["nosebleed", "blood from nostril", "dry mucosa or nose picking", "anticoagulant use", "hypertension"],
 "cir_carotid_dissection": ["neck pain", "headache", "horner syndrome", "transient or fixed neurologic deficit", "recent neck trauma or manipulation"],
 "aortic_aneurysm_unruptured": ["pulsatile abdominal mass", "abdominal or back pain", "older male smoker", "often asymptomatic"],
 "gout": ["sudden hot red swollen joint", "severe joint pain", "big toe joint involvement", "night onset", "previous similar attacks", "high uric acid"],
 "acute_otitis_media": ["ear pain", "fever", "feeling of blocked ear", "child pulling at ear", "recent cold", "bulging red eardrum"],
 "optic_neuritis": ["vision loss in one eye", "pain on moving the eye", "washed out colors", "young adult", "relative afferent pupillary defect"],
 "herpes_zoster": ["burning pain on one side of body", "band-like blistering rash", "rash following a nerve distribution", "tingling before rash", "older age or weakened immunity"],
 "acute_angle_closure_glaucoma": ["severe eye pain", "red eye", "halos around lights", "blurred vision", "headache with nausea and vomiting", "fixed mid-dilated pupil"],
 "giant_cell_arteritis": ["new headache in person over 50", "scalp tenderness", "jaw pain on chewing", "visual disturbance", "fever and malaise", "high ESR"],
 "gca": ["new headache in person over 50", "scalp tenderness", "jaw pain on chewing", "visual disturbance", "fever and malaise", "high ESR"],
 "spontaneous_pneumothorax": ["sudden one-sided chest pain", "shortness of breath", "tall thin young man or smoker", "reduced breath sounds on one side", "onset at rest"],
 "guillain_barre": ["ascending weakness starting in legs", "loss of reflexes", "tingling in feet and hands", "recent infection", "difficulty breathing in severe cases"],
 "cauda_equina": ["low back pain", "saddle numbness", "urinary retention or incontinence", "bilateral leg weakness or sciatica", "bowel incontinence", "reduced anal tone"],
 "septic_arthritis": ["hot swollen painful joint", "inability to move the joint", "fever", "single joint involvement", "recent joint procedure or infection"],
 "septic_arthritis_ortho": ["hot swollen painful joint", "inability to move the joint", "fever", "single joint involvement", "recent joint procedure or infection"],
}

CONF = {
 "pericarditis": ["widespread ST elevation on ECG", "PR segment depression on ECG", "pericardial effusion on echocardiogram"],
 "myocarditis": ["elevated troponin", "myocardial edema on cardiac MRI"],
 "deep_vein_thrombosis": ["thrombus on compression ultrasound", "non-compressible vein on ultrasound"],
 "cholecystitis": ["gallstones with gallbladder wall thickening", "positive sonographic Murphy sign"],
 "cholangitis": ["dilated bile ducts on imaging", "elevated bilirubin"],
 "bowel_obstruction": ["dilated small bowel loops on imaging", "air-fluid levels on abdominal x-ray", "transition point on CT"],
 "diverticulitis": ["colonic wall thickening with inflamed diverticula on CT", "pericolic fat stranding on CT"],
 "testicular_torsion": ["absent testicular blood flow on doppler ultrasound", "twisted spermatic cord on ultrasound"],
 "ovarian_torsion": ["enlarged ovary with absent blood flow on doppler ultrasound", "twisted ovarian pedicle on imaging"],
 "spontaneous_pneumothorax": ["pneumothorax on chest x-ray", "absent lung markings on chest x-ray", "reduced breath sounds on one side"],
 "guillain_barre": ["albuminocytologic dissociation in cerebrospinal fluid", "absent reflexes in affected limbs"],
 "cauda_equina": ["compression of the cauda equina on MRI", "reduced anal sphincter tone", "saddle sensory loss on examination"],
 "septic_arthritis": ["purulent joint fluid", "high synovial fluid white cell count"],
 "septic_arthritis_ortho": ["purulent joint fluid", "high synovial fluid white cell count"],
 "rhabdomyolysis": ["markedly raised creatine kinase", "myoglobin in urine"],
 "gout": ["urate crystals in joint fluid", "negatively birefringent needle-shaped crystals"],
 "giant_cell_arteritis": ["positive temporal artery biopsy", "temporal artery halo sign on ultrasound"],
 "gca": ["positive temporal artery biopsy", "temporal artery halo sign on ultrasound"],
 "optic_neuritis": ["optic nerve enhancement on MRI", "relative afferent pupillary defect on examination"],
 "mesenteric_ischemia": ["filling defect in the mesenteric artery on CT angiography", "elevated lactate"],
 "hyperthyroidism": ["suppressed TSH with raised free T4", "diffuse goiter on examination"],
 "peptic_ulcer_disease": ["ulcer crater seen on endoscopy"],
 "acute_angle_closure_glaucoma": ["raised intraocular pressure", "fixed mid-dilated pupil on examination"],
 "acute_otitis_media": ["bulging red tympanic membrane on otoscopy"],
 "herpes_zoster": ["grouped vesicles in a dermatomal distribution on examination"],
 "pelvic_inflammatory_disease": ["cervical motion tenderness on examination", "mucopurulent cervical discharge on examination"],
 "epididymitis": ["tender swollen epididymis on examination", "raised epididymal blood flow on doppler ultrasound"],
}
prov = {
 "source": "engineering-agent authored summary of widely taught textbook clinical features (general medical-education knowledge); no external dataset or LLM service queried at runtime",
 "clinician_reviewed": False,
 "evidence_level": "unreviewed_general_knowledge",
 "intended_use": "retrieval recall and low-weight feature matching for otherwise empty Tier-2 entries only; makes no diagnostic claim and is NOT a substitute for the Tier-1 deep profiles",
 "scope": "typical_features and (where a defining objective finding is textbook-standard) confirmatory_findings; risk_factors, specific_features, objective_findings, contradictions and minimum_workup intentionally left empty where no reliable source was available",
}
cat = {c['id'] for c in json.load(open('nova_agent/knowledge/tier2_catalog.json'))['conditions']}
missing=[k for k in E if k not in cat]
print('missing',missing, len(E))
json.dump({"provenance": prov, "entries": [dict(id=k, typical_features=v, **({"confirmatory_findings": CONF[k]} if k in CONF else {})) for k, v in E.items() if k in cat]},
          open('nova_agent/knowledge/tier2_enrichment.json','w'), indent=1, ensure_ascii=False)
