#!/usr/bin/env python3
"""Record-level provenance / licence status of every runtime asset (reads the inventory; invents nothing).

Writes docs/compliance/PROVENANCE_STATUS.md. For each asset: path, SHA-256, shipped in the submission, kind,
recorded original source and licence, authorship/generation evidence that actually exists (the inventory's
history_evidence = git commits, which are NOT generation receipts), why it is unresolved, and the realistic
options with the impact of excluding it. A hash match is NOT a permission: this report never upgrades a status.

    python scripts/report_provenance_status.py
"""
import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "artifacts/compliance_hardening/clinical_asset_inventory.json"
OUT = ROOT / "docs/compliance/PROVENANCE_STATUS.md"

CORE_DATA = {  # removing these disables the core reasoning engine or its safety net
    "nova_agent/knowledge/diseases/", "nova_agent/knowledge/red_flags/", "nova_agent/knowledge/guidelines/",
    "nova_agent/knowledge/diagnostic_tests/",
}


def kind(path: str) -> str:
    if path.endswith(".py"):
        return "engine code"
    if path.endswith(".md"):
        return "documentation"
    return "clinical data / rules"


def exclusion_impact(path: str) -> str:
    if path.endswith(".py"):
        return "runtime code: excluding it breaks the package (must be re-authored under a clear licence, not dropped)"
    if any(path.startswith(p) for p in CORE_DATA):
        return "core Tier-1 knowledge / safety rules: excluding it disables diagnosis and can't-miss safety -- not viable without a licensed replacement"
    if path.endswith("tier2_catalog.json"):
        return "1,246 Tier-2 concepts: excluding it removes long-tail candidate coverage (Tier-1 34 profiles remain)"
    if path.endswith("tier2_enrichment.json"):
        return "partial features for 83 Tier-2 concepts: excluding it is feasible; long-tail ranking would weaken (must be re-measured)"
    if path.endswith(".md"):
        return "documentation only: no runtime effect"
    return "must be measured before exclusion"


def main() -> None:
    assets = json.loads(INVENTORY.read_text(encoding="utf-8"))["assets"]
    counts = collections.Counter(a["status"] for a in assets)
    lines = ["# Runtime asset provenance / licence status (record level)", "",
             "Generated by `scripts/report_provenance_status.py` from `artifacts/compliance_hardening/clinical_asset_inventory.json`.",
             "**A current SHA-256 is not a usage right.** No status below was raised by this report; `UNRESOLVED` means the original",
             "source, licence grant, authorship or generation record could not be established from evidence in the repository.",
             "Git commits listed as history are commit records, not generation receipts. No clinician review is claimed.", "",
             "| Status | Assets |", "| --- | --- |"] + [f"| {k} | {v} |" for k, v in counts.most_common()] + [
             "", "Mapping to the requested vocabulary: VERIFIED = VERIFIED, UNRESOLVED = UNRESOLVED, NOT_USED_IN_SUBMISSION = EXCLUDE_FROM_SUBMISSION.",
             "The repository has **no LICENSE file**, so even team-authored code and data carry no stated outbound licence.", "",
             "## Owner decisions that would legitimately resolve the blockers", "",
             "1. **Team authorship + licence (engine code, team-authored heuristics):** if the team (not a third party) authored or",
             "   commissioned these files, the owner can state that in writing and add a repository LICENSE; the inventory can then",
             "   record `TEAM_ORIGINAL_VERIFIED` with that statement as evidence. An engineering agent cannot make this declaration.",
             "2. **AI-generated clinical heuristics:** record the actual tool/model/date/prompt if the owner still has them; otherwise",
             "   keep `UNRESOLVED` and either (a) re-derive the entries from licensed references (MedlinePlus / Orphanet / Disease",
             "   Ontology / Mondo are already integrated with documented terms) and re-run every regression suite, or (b) exclude.",
             "3. **Clinical correctness** is a separate question: an external reference existing for a disease does not validate a rule.",
             "", "## Records", "",
             "| Path | Status | Shipped | Kind | Recorded source / licence | Evidence that exists | Why unresolved | Exclusion impact |",
             "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    for a in sorted(assets, key=lambda x: (x["status"] != "UNRESOLVED", x["path"])):
        history = a.get("history_evidence") or []
        evidence = f"{len(history)} git commit record(s); first {history[-1].split('|')[1][:10]}" if history else "embedded source/terms records"
        reason = ("source, licence, authorship and generation record not recoverable" if a["status"] == "UNRESOLVED"
                  else "-" if a["status"] == "VERIFIED" else "not bundled")
        source = f"{(a.get('original_source') or '')[:70]} / {(a.get('license') or '')[:40]}"
        lines.append(f"| `{a['path']}` | {a['status']} | {'yes' if a.get('submission_included') else 'no'} | {kind(a['path'])} | "
                     f"{source.replace('|', '/')} | {evidence} | {reason} | {exclusion_impact(a['path']) if a['status'] == 'UNRESOLVED' else '-'} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {dict(counts)}")


if __name__ == "__main__":
    main()
