"""Large Tier-2 structured-catalog expansion (5,000-diagnosis round).

Adds a broad set of additional real, named clinical conditions organized by ICD-10 chapter/block so
the Tier-2 structured layer reaches >=1,500 entries. Every entry is a genuine clinical entity with a
real canonical name, a specialty category, and (where confident) an ICD-10 anchor.

HONESTY RULES (unchanged, do NOT relax):
  - No fabricated discriminating tests / confirmatory findings / thresholds — that is Tier-1 (deep).
    Tier-2 stays "structured but shallow": name / aliases / category / urgency-hint / ICD-10 anchor.
  - Where urgency is not clinically well-established for the generic entity, it is left None.
  - Aliases are only added when they are real, well-known synonyms/abbreviations.
  - Global id + canonical-name de-duplication is enforced by the merger in build_tier2_catalog.py,
    so overlaps with the base/extra sets are skipped, never double-counted.

Tuple form matches build_tier2_catalog: (id, name, category, urgency|None, icd10|None, [aliases]).
"""

from __future__ import annotations

from typing import List

C = List[tuple]


def _mk(prefix: str, category: str, items: List[tuple]) -> C:
    """items: (slug, name, urgency|None, icd10|None, [aliases]). Namespaced id = <prefix>_<slug>."""
    out: C = []
    for slug, name, urgency, icd10, aliases in items:
        out.append((f"{prefix}_{slug}", name, category, urgency, icd10, aliases))
    return out


# --- Infectious diseases (ICD-10 A00–B99) ----------------------------------------------------
INFECTIOUS = _mk("inf", "infectious", [
    ("shigellosis", "Shigellosis", "URGENT", "A03.9", ["shigella dysentery"]),
    ("salmonellosis", "Salmonella Enteritis", "URGENT", "A02.0", ["salmonella"]),
    ("campylobacter", "Campylobacter Enteritis", "URGENT", "A04.5", []),
    ("cholera_inf", "Cholera", "CRITICAL", "A00.9", []),
    ("botulism", "Botulism", "CRITICAL", "A05.1", []),
    ("amebiasis", "Amebiasis", "URGENT", "A06.9", ["amebic dysentery"]),
    ("giardiasis", "Giardiasis", "ROUTINE", "A07.1", []),
    ("cryptosporidiosis", "Cryptosporidiosis", "URGENT", "A07.2", []),
    ("plague", "Plague", "CRITICAL", "A20.9", ["yersinia pestis"]),
    ("tularemia", "Tularemia", "URGENT", "A21.9", []),
    ("anthrax", "Anthrax", "CRITICAL", "A22.9", []),
    ("listeriosis", "Listeriosis", "CRITICAL", "A32.9", ["listeria"]),
    ("diphtheria", "Diphtheria", "CRITICAL", "A36.9", []),
    ("gonorrhea", "Gonococcal Infection", "URGENT", "A54.9", ["gonorrhea"]),
    ("syphilis", "Syphilis", "URGENT", "A53.9", []),
    ("chlamydia", "Chlamydial Infection", "URGENT", "A56.9", []),
    ("relapsing_fever", "Relapsing Fever", "URGENT", "A68.9", []),
    ("q_fever", "Q Fever", "URGENT", "A78", ["coxiella"]),
    ("rocky_mountain", "Rocky Mountain Spotted Fever", "CRITICAL", "A77.0", ["rmsf"]),
    ("typhus", "Typhus Fever", "URGENT", "A75.9", []),
    ("west_nile", "West Nile Virus Infection", "URGENT", "A92.30", []),
    ("chikungunya", "Chikungunya", "URGENT", "A92.0", []),
    ("zika", "Zika Virus Disease", "URGENT", "A92.5", []),
    ("yellow_fever", "Yellow Fever", "CRITICAL", "A95.9", []),
    ("ebola", "Ebola Virus Disease", "CRITICAL", "A98.4", []),
    ("hemorrhagic_fever", "Viral Hemorrhagic Fever", "CRITICAL", "A99", []),
    ("hantavirus", "Hantavirus Infection", "CRITICAL", "B33.4", []),
    ("cmv", "Cytomegalovirus Disease", "URGENT", "B25.9", ["cmv"]),
    ("ebv", "Epstein-Barr Virus Infection", "ROUTINE", "B27.90", ["ebv"]),
    ("hsv_encephalitis", "Herpes Simplex Encephalitis", "CRITICAL", "B00.4", []),
    ("candidiasis_mucosal", "Mucosal Candidiasis", "ROUTINE", "B37.9", ["thrush"]),
    ("aspergillosis", "Aspergillosis", "URGENT", "B44.9", []),
    ("cryptococcosis", "Cryptococcosis", "CRITICAL", "B45.9", []),
    ("histoplasmosis", "Histoplasmosis", "URGENT", "B39.9", []),
    ("coccidioidomycosis", "Coccidioidomycosis", "URGENT", "B38.9", ["valley fever"]),
    ("pneumocystis_inf", "Pneumocystis jirovecii Pneumonia", "CRITICAL", "B59", ["pjp", "pcp"]),
    ("toxoplasmosis", "Toxoplasmosis", "URGENT", "B58.9", []),
    ("schistosomiasis", "Schistosomiasis", "URGENT", "B65.9", []),
    ("echinococcosis", "Echinococcosis", "URGENT", "B67.90", ["hydatid disease"]),
    ("cysticercosis", "Cysticercosis", "URGENT", "B69.9", ["neurocysticercosis"]),
    ("strongyloidiasis", "Strongyloidiasis", "URGENT", "B78.9", []),
    ("ascariasis", "Ascariasis", "ROUTINE", "B77.9", []),
    ("hookworm", "Hookworm Disease", "ROUTINE", "B76.9", []),
    ("scabies_inf", "Scabies", "ROUTINE", "B86", []),
    ("pediculosis", "Pediculosis (Lice)", "ROUTINE", "B85.2", []),
    ("mrsa", "MRSA Infection", "URGENT", "A49.02", ["methicillin-resistant staph aureus"]),
    ("vre", "Vancomycin-Resistant Enterococcus", "URGENT", "A49.09", ["vre"]),
    ("bacteremia", "Bacteremia", "CRITICAL", "R78.81", []),
    ("catheter_infection", "Catheter-Related Bloodstream Infection", "CRITICAL", "T80.211A", ["clabsi"]),
    ("surgical_site_infection", "Surgical Site Infection", "URGENT", "T81.4XXA", ["ssi"]),
])

# --- Neoplasms (ICD-10 C00–D49) --------------------------------------------------------------
NEOPLASMS = _mk("neo", "oncology", [
    ("oral_cavity_ca", "Oral Cavity Cancer", "URGENT", "C06.9", []),
    ("tongue_ca", "Tongue Cancer", "URGENT", "C02.9", []),
    ("salivary_gland_ca", "Salivary Gland Cancer", "URGENT", "C08.9", []),
    ("hypopharyngeal_ca", "Hypopharyngeal Cancer", "URGENT", "C13.9", []),
    ("small_intestine_ca", "Small Intestine Cancer", "URGENT", "C17.9", []),
    ("anal_ca", "Anal Cancer", "URGENT", "C21.0", []),
    ("gallbladder_ca", "Gallbladder Cancer", "URGENT", "C23", []),
    ("bile_duct_ca", "Cholangiocarcinoma", "URGENT", "C24.0", ["bile duct cancer"]),
    ("nasal_sinus_ca", "Nasal Cavity and Sinus Cancer", "URGENT", "C30.0", []),
    ("thymoma", "Thymoma", "URGENT", "C37", []),
    ("bone_sarcoma", "Bone Sarcoma", "URGENT", "C41.9", ["osteosarcoma"]),
    ("kaposi_sarcoma", "Kaposi Sarcoma", "URGENT", "C46.9", []),
    ("soft_tissue_sarcoma", "Soft Tissue Sarcoma", "URGENT", "C49.9", []),
    ("vulvar_ca", "Vulvar Cancer", "URGENT", "C51.9", []),
    ("vaginal_ca", "Vaginal Cancer", "URGENT", "C52", []),
    ("penile_ca", "Penile Cancer", "URGENT", "C60.9", []),
    ("testicular_ca", "Testicular Cancer", "URGENT", "C62.90", []),
    ("ureteral_ca", "Ureteral Cancer", "URGENT", "C66.9", []),
    ("adrenal_ca", "Adrenal Cortical Carcinoma", "URGENT", "C74.00", []),
    ("gist", "Gastrointestinal Stromal Tumor", "URGENT", "C49.A0", ["gist"]),
    ("neuroblastoma", "Neuroblastoma", "URGENT", "C74.90", []),
    ("wilms_tumor", "Wilms Tumor", "URGENT", "C64.9", ["nephroblastoma"]),
    ("retinoblastoma", "Retinoblastoma", "URGENT", "C69.20", []),
    ("mycosis_fungoides", "Mycosis Fungoides", "URGENT", "C84.00", []),
    ("plasmacytoma", "Solitary Plasmacytoma", "URGENT", "C90.30", []),
    ("myeloproliferative", "Myeloproliferative Neoplasm", "URGENT", "D47.1", []),
    ("carcinoid", "Carcinoid Tumor", "URGENT", "C7A.00", ["neuroendocrine tumor"]),
    ("mesothelioma_neo", "Mesothelioma", "URGENT", "C45.9", []),
    ("cns_lymphoma", "Primary CNS Lymphoma", "URGENT", "C85.9", []),
    ("glioblastoma", "Glioblastoma", "CRITICAL", "C71.9", ["gbm"]),
    ("meningioma", "Meningioma", "URGENT", "D32.9", []),
    ("pituitary_adenoma", "Pituitary Adenoma", "URGENT", "D35.2", []),
    ("colonic_polyp", "Colonic Adenomatous Polyp", "ROUTINE", "K63.5", []),
    ("cervical_intraepithelial", "Cervical Intraepithelial Neoplasia", "ROUTINE", "N87.9", ["cin"]),
    ("monoclonal_gammopathy", "Monoclonal Gammopathy of Undetermined Significance", "ROUTINE", "D47.2", ["mgus"]),
])

# --- Blood/immune (ICD-10 D50–D89) -----------------------------------------------------------
HEME_IMMUNE = _mk("hem", "hematology", [
    ("anemia_chronic_disease", "Anemia of Chronic Disease", "ROUTINE", "D63.8", []),
    ("sideroblastic_anemia", "Sideroblastic Anemia", "URGENT", "D64.3", []),
    ("g6pd_hem", "G6PD Deficiency", "URGENT", "D55.0", []),
    ("hereditary_spherocytosis", "Hereditary Spherocytosis", "URGENT", "D58.0", []),
    ("paroxysmal_nocturnal", "Paroxysmal Nocturnal Hemoglobinuria", "URGENT", "D59.5", ["pnh"]),
    ("pure_red_cell_aplasia", "Pure Red Cell Aplasia", "URGENT", "D60.9", []),
    ("agranulocytosis", "Agranulocytosis", "CRITICAL", "D70.9", []),
    ("factor_v_leiden", "Factor V Leiden Thrombophilia", "ROUTINE", "D68.51", []),
    ("protein_c_deficiency", "Protein C Deficiency", "URGENT", "D68.59", []),
    ("antithrombin_deficiency", "Antithrombin III Deficiency", "URGENT", "D68.59", []),
    ("heparin_induced_thrombocytopenia", "Heparin-Induced Thrombocytopenia", "CRITICAL", "D75.82", ["hit"]),
    ("hemophagocytic", "Hemophagocytic Lymphohistiocytosis", "CRITICAL", "D76.1", ["hlh"]),
    ("methemoglobinemia", "Methemoglobinemia", "CRITICAL", "D74.9", []),
    ("hypogammaglobulinemia", "Hypogammaglobulinemia", "URGENT", "D80.1", []),
    ("digeorge", "DiGeorge Syndrome", "URGENT", "D82.1", []),
    ("wiskott_aldrich", "Wiskott-Aldrich Syndrome", "URGENT", "D82.0", []),
    ("complement_deficiency", "Complement Deficiency", "URGENT", "D84.1", []),
    ("mast_cell_activation", "Mast Cell Activation Syndrome", "URGENT", "D89.42", ["mcas"]),
    ("mastocytosis", "Systemic Mastocytosis", "URGENT", "D47.02", []),
    ("cryoglobulinemia", "Cryoglobulinemia", "URGENT", "D89.1", []),
])

# --- Endocrine/metabolic (ICD-10 E00–E89) ----------------------------------------------------
ENDO_METAB = _mk("end", "endocrine_metabolic", [
    ("congenital_hypothyroid", "Congenital Hypothyroidism", "URGENT", "E03.1", []),
    ("thyroiditis_hashimoto", "Hashimoto Thyroiditis", "ROUTINE", "E06.3", []),
    ("goiter", "Nontoxic Goiter", "ROUTINE", "E04.9", []),
    ("hyperaldosteronism", "Hyperaldosteronism", "URGENT", "E26.9", ["conn syndrome"]),
    ("adrenal_incidentaloma", "Adrenal Incidentaloma", "ROUTINE", "E27.8", []),
    ("mody", "Maturity-Onset Diabetes of the Young", "ROUTINE", "E13.9", ["mody"]),
    ("type1_diabetes", "Type 1 Diabetes Mellitus", "URGENT", "E10.9", ["t1dm"]),
    ("hypoglycemia_reactive", "Reactive Hypoglycemia", "ROUTINE", "E16.1", []),
    ("insulinoma", "Insulinoma", "URGENT", "E16.1", []),
    ("carcinoid_syndrome", "Carcinoid Syndrome", "URGENT", "E34.0", []),
    ("men1", "Multiple Endocrine Neoplasia Type 1", "URGENT", "E31.21", ["men1"]),
    ("men2", "Multiple Endocrine Neoplasia Type 2", "URGENT", "E31.22", ["men2"]),
    ("vitamin_d_deficiency", "Vitamin D Deficiency", "ROUTINE", "E55.9", []),
    ("scurvy", "Scurvy (Vitamin C Deficiency)", "URGENT", "E54", []),
    ("pellagra", "Pellagra (Niacin Deficiency)", "URGENT", "E52", []),
    ("beriberi", "Beriberi (Thiamine Deficiency)", "URGENT", "E51.11", []),
    ("kwashiorkor", "Kwashiorkor", "CRITICAL", "E40", []),
    ("marasmus", "Nutritional Marasmus", "CRITICAL", "E41", []),
    ("obesity", "Obesity", "ROUTINE", "E66.9", []),
    ("metabolic_syndrome", "Metabolic Syndrome", "ROUTINE", "E88.81", []),
    ("hyperlipidemia", "Hyperlipidemia", "ROUTINE", "E78.5", ["dyslipidemia"]),
    ("familial_hypercholesterolemia", "Familial Hypercholesterolemia", "URGENT", "E78.01", []),
    ("gout_metab", "Hyperuricemia", "ROUTINE", "E79.0", []),
    ("hypomagnesemia", "Hypomagnesemia", "URGENT", "E83.42", []),
    ("hypophosphatemia", "Hypophosphatemia", "URGENT", "E83.39", []),
    ("refeeding_syndrome", "Refeeding Syndrome", "CRITICAL", "E87.8", []),
    ("lactic_acidosis", "Lactic Acidosis", "CRITICAL", "E87.2", []),
    ("amyloidosis", "Amyloidosis", "URGENT", "E85.9", []),
    ("hemochromatosis_end", "Hereditary Hemochromatosis", "ROUTINE", "E83.110", []),
])

# --- Mental/behavioral (ICD-10 F01–F99) ------------------------------------------------------
PSYCH = _mk("psy", "psychiatric", [
    ("delirium_psy", "Delirium", "URGENT", "F05", []),
    ("dementia_lewy", "Dementia with Lewy Bodies", "ROUTINE", "G31.83", []),
    ("frontotemporal_dementia", "Frontotemporal Dementia", "ROUTINE", "G31.09", []),
    ("substance_use_alcohol", "Alcohol Use Disorder", "URGENT", "F10.20", []),
    ("opioid_use_disorder", "Opioid Use Disorder", "URGENT", "F11.20", []),
    ("stimulant_use_disorder", "Stimulant Use Disorder", "URGENT", "F15.20", []),
    ("cannabis_use_disorder", "Cannabis Use Disorder", "ROUTINE", "F12.20", []),
    ("schizoaffective", "Schizoaffective Disorder", "URGENT", "F25.9", []),
    ("delusional_disorder", "Delusional Disorder", "URGENT", "F22", []),
    ("bipolar_mania", "Bipolar Disorder, Manic Episode", "URGENT", "F31.10", []),
    ("persistent_depressive", "Persistent Depressive Disorder", "ROUTINE", "F34.1", ["dysthymia"]),
    ("postpartum_depression", "Postpartum Depression", "URGENT", "F53.0", []),
    ("ocd", "Obsessive-Compulsive Disorder", "ROUTINE", "F42.9", ["ocd"]),
    ("social_anxiety", "Social Anxiety Disorder", "ROUTINE", "F40.10", []),
    ("bulimia", "Bulimia Nervosa", "URGENT", "F50.2", []),
    ("binge_eating", "Binge Eating Disorder", "ROUTINE", "F50.81", []),
    ("insomnia_disorder", "Insomnia Disorder", "ROUTINE", "F51.01", []),
    ("adhd", "Attention-Deficit/Hyperactivity Disorder", "ROUTINE", "F90.9", ["adhd"]),
    ("autism_spectrum", "Autism Spectrum Disorder", "ROUTINE", "F84.0", ["asd"]),
    ("conversion_disorder", "Functional Neurological Disorder", "ROUTINE", "F44.9", ["conversion disorder"]),
    ("somatic_symptom", "Somatic Symptom Disorder", "ROUTINE", "F45.1", []),
    ("borderline_personality", "Borderline Personality Disorder", "URGENT", "F60.3", []),
])

# --- Nervous system (ICD-10 G00–G99) ---------------------------------------------------------
NEURO = _mk("neu", "neuro", [
    ("meningitis_viral", "Viral Meningitis", "URGENT", "A87.9", []),
    ("brain_abscess_neu", "Brain Abscess", "CRITICAL", "G06.0", []),
    ("epidural_abscess", "Spinal Epidural Abscess", "CRITICAL", "G06.1", []),
    ("parkinsonism_atypical", "Atypical Parkinsonism", "URGENT", "G23.9", []),
    ("progressive_supranuclear", "Progressive Supranuclear Palsy", "URGENT", "G23.1", ["psp"]),
    ("dystonia", "Dystonia", "ROUTINE", "G24.9", []),
    ("tourette", "Tourette Syndrome", "ROUTINE", "F95.2", []),
    ("restless_legs", "Restless Legs Syndrome", "ROUTINE", "G25.81", ["rls"]),
    ("narcolepsy", "Narcolepsy", "ROUTINE", "G47.419", []),
    ("cluster_headache_neu", "Cluster Headache", "URGENT", "G44.009", []),
    ("medication_overuse_headache", "Medication Overuse Headache", "ROUTINE", "G44.40", []),
    ("chronic_migraine", "Chronic Migraine", "ROUTINE", "G43.709", []),
    ("cerebral_palsy", "Cerebral Palsy", "ROUTINE", "G80.9", []),
    ("spina_bifida", "Spina Bifida", "URGENT", "Q05.9", []),
    ("syringomyelia", "Syringomyelia", "URGENT", "G95.0", []),
    ("cervical_myelopathy", "Cervical Spondylotic Myelopathy", "URGENT", "M47.12", []),
    ("radiculopathy", "Cervical Radiculopathy", "ROUTINE", "M54.12", []),
    ("brachial_plexopathy", "Brachial Plexopathy", "URGENT", "G54.0", []),
    ("chronic_inflammatory_demyelinating", "Chronic Inflammatory Demyelinating Polyneuropathy", "URGENT", "G61.81", ["cidp"]),
    ("diabetic_neuropathy", "Diabetic Peripheral Neuropathy", "ROUTINE", "E11.42", []),
    ("bells_palsy_neu", "Bell Palsy", "URGENT", "G51.0", []),
    ("hemifacial_spasm", "Hemifacial Spasm", "ROUTINE", "G51.3", []),
    ("myoclonus", "Myoclonus", "URGENT", "G25.3", []),
    ("hydrocephalus", "Hydrocephalus", "URGENT", "G91.9", []),
    ("pseudotumor", "Idiopathic Intracranial Hypertension", "URGENT", "G93.2", ["pseudotumor cerebri"]),
    ("anoxic_brain_injury", "Anoxic Brain Injury", "CRITICAL", "G93.1", []),
    ("locked_in", "Locked-In Syndrome", "CRITICAL", "G83.5", []),
    ("chronic_fatigue", "Myalgic Encephalomyelitis / Chronic Fatigue Syndrome", "ROUTINE", "G93.32", ["me/cfs"]),
])

# --- Eye/adnexa (H00–H59) --------------------------------------------------------------------
EYE = _mk("eye", "ophthalmology", [
    ("blepharitis", "Blepharitis", "ROUTINE", "H01.009", []),
    ("chalazion", "Chalazion", "ROUTINE", "H00.19", []),
    ("hordeolum", "Hordeolum (Stye)", "ROUTINE", "H00.019", []),
    ("dacryocystitis", "Dacryocystitis", "URGENT", "H04.309", []),
    ("scleritis", "Scleritis", "URGENT", "H15.009", []),
    ("episcleritis", "Episcleritis", "ROUTINE", "H15.109", []),
    ("corneal_ulcer", "Corneal Ulcer", "URGENT", "H16.009", []),
    ("cataract", "Cataract", "ROUTINE", "H26.9", []),
    ("open_angle_glaucoma", "Primary Open-Angle Glaucoma", "URGENT", "H40.11X0", []),
    ("macular_degeneration", "Age-Related Macular Degeneration", "URGENT", "H35.30", ["amd"]),
    ("retinal_vein_branch", "Branch Retinal Vein Occlusion", "URGENT", "H34.83", []),
    ("vitreous_hemorrhage", "Vitreous Hemorrhage", "URGENT", "H43.10", []),
    ("papilledema", "Papilledema", "CRITICAL", "H47.10", []),
    ("amaurosis_fugax", "Amaurosis Fugax", "CRITICAL", "G45.3", []),
    ("strabismus", "Strabismus", "ROUTINE", "H50.9", []),
    ("keratoconus", "Keratoconus", "ROUTINE", "H18.60", []),
    ("dry_eye", "Dry Eye Syndrome", "ROUTINE", "H04.129", []),
])

# --- Ear (H60–H95) ---------------------------------------------------------------------------
EAR = _mk("ear", "ent", [
    ("cerumen_impaction", "Cerumen Impaction", "ROUTINE", "H61.20", []),
    ("tympanic_perforation", "Tympanic Membrane Perforation", "URGENT", "H72.90", []),
    ("cholesteatoma", "Cholesteatoma", "URGENT", "H71.90", []),
    ("labyrinthitis", "Labyrinthitis", "URGENT", "H83.09", []),
    ("tinnitus", "Tinnitus", "ROUTINE", "H93.19", []),
    ("presbycusis", "Presbycusis", "ROUTINE", "H91.10", []),
    ("noise_hearing_loss", "Noise-Induced Hearing Loss", "ROUTINE", "H83.3X9", []),
    ("acoustic_neuroma", "Vestibular Schwannoma", "URGENT", "D33.3", ["acoustic neuroma"]),
])

# --- Circulatory (I00–I99) -------------------------------------------------------------------
CIRC = _mk("cir", "cardiovascular", [
    ("acute_rheumatic_fever", "Acute Rheumatic Fever", "URGENT", "I00", []),
    ("mitral_valve_prolapse", "Mitral Valve Prolapse", "ROUTINE", "I34.1", ["mvp"]),
    ("pulmonic_stenosis", "Pulmonic Valve Stenosis", "URGENT", "I37.0", []),
    ("prosthetic_valve_dysfunction", "Prosthetic Valve Dysfunction", "CRITICAL", "T82.09XA", []),
    ("cardiac_sarcoidosis", "Cardiac Sarcoidosis", "URGENT", "D86.85", []),
    ("left_ventricular_hypertrophy", "Left Ventricular Hypertrophy", "ROUTINE", "I51.7", ["lvh"]),
    ("cor_pulmonale", "Cor Pulmonale", "URGENT", "I27.81", []),
    ("first_degree_av_block", "First-Degree AV Block", "ROUTINE", "I44.0", []),
    ("left_bundle_branch", "Left Bundle Branch Block", "URGENT", "I44.7", ["lbbb"]),
    ("right_bundle_branch", "Right Bundle Branch Block", "ROUTINE", "I45.10", ["rbbb"]),
    ("sinus_bradycardia", "Sinus Bradycardia", "ROUTINE", "R00.1", []),
    ("sinus_tachycardia", "Sinus Tachycardia", "ROUTINE", "R00.0", []),
    ("premature_atrial", "Premature Atrial Contractions", "ROUTINE", "I49.1", ["pac"]),
    ("orthostatic_hypotension_cir", "Orthostatic Hypotension", "URGENT", "I95.1", []),
    ("essential_hypertension", "Essential Hypertension", "ROUTINE", "I10", []),
    ("secondary_hypertension", "Secondary Hypertension", "URGENT", "I15.9", []),
    ("intracranial_aneurysm", "Unruptured Intracranial Aneurysm", "URGENT", "I67.1", []),
    ("moyamoya", "Moyamoya Disease", "URGENT", "I67.5", []),
    ("mesenteric_vein_thrombosis", "Mesenteric Venous Thrombosis", "CRITICAL", "K55.0", []),
    ("renal_vein_thrombosis", "Renal Vein Thrombosis", "URGENT", "I82.3", []),
    ("varicose_veins", "Varicose Veins", "ROUTINE", "I83.90", []),
    ("thromboangiitis_cir", "Buerger Disease", "URGENT", "I73.1", []),
    ("aortitis", "Aortitis", "URGENT", "I77.6", []),
    ("takayasu", "Takayasu Arteritis", "URGENT", "M31.4", []),
    ("carotid_dissection", "Carotid Artery Dissection", "CRITICAL", "I77.71", []),
    ("vertebral_dissection", "Vertebral Artery Dissection", "CRITICAL", "I77.74", []),
])

# --- Respiratory (J00–J99) -------------------------------------------------------------------
RESP = _mk("res", "pulmonary", [
    ("acute_sinusitis_res", "Acute Sinusitis", "ROUTINE", "J01.90", []),
    ("chronic_sinusitis", "Chronic Sinusitis", "ROUTINE", "J32.9", []),
    ("acute_pharyngitis", "Acute Pharyngitis", "ROUTINE", "J02.9", []),
    ("strep_pharyngitis", "Streptococcal Pharyngitis", "URGENT", "J02.0", ["strep throat"]),
    ("acute_laryngitis", "Acute Laryngitis", "ROUTINE", "J04.0", []),
    ("chronic_rhinitis", "Chronic Rhinitis", "ROUTINE", "J31.0", []),
    ("nasal_polyps", "Nasal Polyps", "ROUTINE", "J33.9", []),
    ("vocal_cord_paralysis", "Vocal Cord Paralysis", "URGENT", "J38.00", []),
    ("chronic_bronchitis", "Chronic Bronchitis", "ROUTINE", "J42", []),
    ("emphysema", "Emphysema", "ROUTINE", "J43.9", []),
    ("bronchopneumonia", "Bronchopneumonia", "URGENT", "J18.0", []),
    ("lung_abscess", "Lung Abscess", "URGENT", "J85.2", []),
    ("empyema_res", "Pleural Empyema", "URGENT", "J86.9", []),
    ("bronchopulmonary_dysplasia", "Bronchopulmonary Dysplasia", "URGENT", "P27.1", ["bpd"]),
    ("occupational_lung", "Pneumoconiosis", "URGENT", "J64", ["pneumoconiosis"]),
    ("silicosis", "Silicosis", "URGENT", "J62.8", []),
    ("asbestosis", "Asbestosis", "URGENT", "J61", []),
    ("hypersensitivity_pneumonitis_res", "Hypersensitivity Pneumonitis", "URGENT", "J67.9", []),
    ("eosinophilic_pneumonia", "Eosinophilic Pneumonia", "URGENT", "J82", []),
    ("pulmonary_alveolar_proteinosis", "Pulmonary Alveolar Proteinosis", "URGENT", "J84.01", []),
    ("respiratory_failure_chronic", "Chronic Respiratory Failure", "URGENT", "J96.10", []),
    ("mediastinitis", "Mediastinitis", "CRITICAL", "J98.51", []),
    ("chylothorax", "Chylothorax", "URGENT", "J94.0", []),
])

# --- Digestive (K00–K95) ---------------------------------------------------------------------
GI = _mk("gi", "abdominal_gi", [
    ("dental_abscess", "Dental Abscess", "URGENT", "K04.7", []),
    ("sialadenitis", "Sialadenitis", "URGENT", "K11.20", []),
    ("gerd_gi", "Gastroesophageal Reflux Disease", "ROUTINE", "K21.9", ["gerd"]),
    ("barrett_esophagus", "Barrett Esophagus", "ROUTINE", "K22.70", []),
    ("esophageal_stricture", "Esophageal Stricture", "URGENT", "K22.2", []),
    ("hiatal_hernia", "Hiatal Hernia", "ROUTINE", "K44.9", []),
    ("gastroparesis_gi", "Gastroparesis", "ROUTINE", "K31.84", []),
    ("duodenal_ulcer", "Duodenal Ulcer", "URGENT", "K26.9", []),
    ("gastric_ulcer", "Gastric Ulcer", "URGENT", "K25.9", []),
    ("malabsorption", "Malabsorption Syndrome", "ROUTINE", "K90.9", []),
    ("lactose_intolerance", "Lactose Intolerance", "ROUTINE", "E73.9", []),
    ("microscopic_colitis", "Microscopic Colitis", "ROUTINE", "K52.831", []),
    ("appendiceal_mucocele", "Appendiceal Mucocele", "URGENT", "K38.8", []),
    ("inguinal_hernia", "Inguinal Hernia", "ROUTINE", "K40.90", []),
    ("incarcerated_hernia", "Incarcerated Hernia", "CRITICAL", "K46.0", []),
    ("intestinal_ischemia", "Chronic Mesenteric Ischemia", "URGENT", "K55.1", []),
    ("angiodysplasia", "Intestinal Angiodysplasia", "URGENT", "K55.21", []),
    ("fecal_impaction", "Fecal Impaction", "URGENT", "K56.41", []),
    ("perforated_ulcer", "Perforated Peptic Ulcer", "CRITICAL", "K27.5", []),
    ("anal_abscess", "Anorectal Abscess", "URGENT", "K61.0", []),
    ("anal_fistula", "Anal Fistula", "ROUTINE", "K60.3", []),
    ("proctitis", "Proctitis", "URGENT", "K62.89", []),
    ("liver_abscess", "Pyogenic Liver Abscess", "CRITICAL", "K75.0", []),
    ("autoimmune_hepatitis", "Autoimmune Hepatitis", "URGENT", "K75.4", []),
    ("primary_sclerosing_cholangitis", "Primary Sclerosing Cholangitis", "URGENT", "K83.01", ["psc"]),
    ("pancreatic_pseudocyst", "Pancreatic Pseudocyst", "URGENT", "K86.3", []),
    ("peritonitis_gi", "Peritonitis", "CRITICAL", "K65.9", []),
    ("volvulus", "Intestinal Volvulus", "CRITICAL", "K56.2", []),
    ("short_bowel", "Short Bowel Syndrome", "URGENT", "K91.2", []),
])

# --- Skin (L00–L99) --------------------------------------------------------------------------
DERM = _mk("der", "dermatology", [
    ("impetigo", "Impetigo", "ROUTINE", "L01.00", []),
    ("folliculitis", "Folliculitis", "ROUTINE", "L73.9", []),
    ("hidradenitis", "Hidradenitis Suppurativa", "URGENT", "L73.2", []),
    ("cutaneous_abscess", "Cutaneous Abscess", "URGENT", "L02.91", []),
    ("seborrheic_dermatitis", "Seborrheic Dermatitis", "ROUTINE", "L21.9", []),
    ("rosacea", "Rosacea", "ROUTINE", "L71.9", []),
    ("acne", "Acne Vulgaris", "ROUTINE", "L70.0", []),
    ("lichen_planus", "Lichen Planus", "ROUTINE", "L43.9", []),
    ("pityriasis_rosea", "Pityriasis Rosea", "ROUTINE", "L42", []),
    ("vitiligo", "Vitiligo", "ROUTINE", "L80", []),
    ("alopecia_areata", "Alopecia Areata", "ROUTINE", "L63.9", []),
    ("erythema_nodosum", "Erythema Nodosum", "URGENT", "L52", []),
    ("dermatitis_herpetiformis", "Dermatitis Herpetiformis", "ROUTINE", "L13.0", []),
    ("pressure_ulcer", "Pressure Ulcer", "URGENT", "L89.90", ["decubitus ulcer"]),
    ("cellulitis_der", "Cellulitis", "URGENT", "L03.90", []),
    ("necrotizing_der", "Necrotizing Fasciitis", "CRITICAL", "M72.6", []),
    ("dermatomyositis_der", "Dermatomyositis", "URGENT", "M33.90", []),
    ("actinic_keratosis", "Actinic Keratosis", "ROUTINE", "L57.0", []),
    ("drug_eruption", "Drug Eruption", "URGENT", "L27.0", []),
    ("photosensitivity", "Photosensitivity Dermatitis", "ROUTINE", "L56.8", []),
])

# --- Musculoskeletal (M00–M99) ---------------------------------------------------------------
MSK = _mk("msk", "musculoskeletal", [
    ("reactive_arthritis_msk", "Reactive Arthritis", "ROUTINE", "M02.9", []),
    ("psoriatic_arthritis_msk", "Psoriatic Arthritis", "ROUTINE", "L40.50", []),
    ("juvenile_idiopathic_arthritis", "Juvenile Idiopathic Arthritis", "URGENT", "M08.00", ["jia"]),
    ("osteoarthritis_hip", "Hip Osteoarthritis", "ROUTINE", "M16.9", []),
    ("osteoarthritis_knee", "Knee Osteoarthritis", "ROUTINE", "M17.9", []),
    ("bursitis", "Bursitis", "ROUTINE", "M71.9", []),
    ("tendinitis", "Tendinitis", "ROUTINE", "M77.9", []),
    ("lateral_epicondylitis", "Lateral Epicondylitis", "ROUTINE", "M77.10", ["tennis elbow"]),
    ("de_quervain", "De Quervain Tenosynovitis", "ROUTINE", "M65.4", []),
    ("fibromyalgia", "Fibromyalgia", "ROUTINE", "M79.7", []),
    ("polymyalgia_msk", "Polymyalgia Rheumatica", "URGENT", "M35.3", []),
    ("costochondritis", "Costochondritis", "ROUTINE", "M94.0", []),
    ("spinal_stenosis", "Lumbar Spinal Stenosis", "URGENT", "M48.06", []),
    ("spondylolisthesis", "Spondylolisthesis", "ROUTINE", "M43.10", []),
    ("scoliosis", "Scoliosis", "ROUTINE", "M41.9", []),
    ("osteomyelitis_msk", "Osteomyelitis", "URGENT", "M86.9", []),
    ("avascular_necrosis", "Avascular Necrosis", "URGENT", "M87.9", ["osteonecrosis"]),
    ("pagets_bone", "Paget Disease of Bone", "ROUTINE", "M88.9", []),
    ("osteomalacia", "Osteomalacia", "URGENT", "M83.9", []),
    ("osteoporosis_msk", "Osteoporosis", "ROUTINE", "M81.0", []),
    ("rhabdomyolysis_msk", "Rhabdomyolysis", "URGENT", "M62.82", []),
    ("myositis_ossificans", "Myositis Ossificans", "ROUTINE", "M61.50", []),
    ("adhesive_capsulitis_msk", "Adhesive Capsulitis", "ROUTINE", "M75.00", []),
    ("dupuytren", "Dupuytren Contracture", "ROUTINE", "M72.0", []),
    ("gout_arthropathy", "Gouty Arthropathy", "URGENT", "M10.9", []),
])

# --- Genitourinary (N00–N99) -----------------------------------------------------------------
GU = _mk("gu", "genitourinary", [
    ("iga_nephropathy", "IgA Nephropathy", "URGENT", "N02.8", []),
    ("minimal_change", "Minimal Change Disease", "URGENT", "N04.0", []),
    ("focal_segmental_glomerulosclerosis", "Focal Segmental Glomerulosclerosis", "URGENT", "N04.1", ["fsgs"]),
    ("membranous_nephropathy", "Membranous Nephropathy", "URGENT", "N04.2", []),
    ("lupus_nephritis", "Lupus Nephritis", "URGENT", "M32.14", []),
    ("interstitial_nephritis", "Acute Interstitial Nephritis", "URGENT", "N10", []),
    ("renal_papillary_necrosis", "Renal Papillary Necrosis", "URGENT", "N17.2", []),
    ("hydronephrosis_gu", "Hydronephrosis", "URGENT", "N13.30", []),
    ("vesicoureteral_reflux", "Vesicoureteral Reflux", "ROUTINE", "N13.70", []),
    ("neurogenic_bladder", "Neurogenic Bladder", "URGENT", "N31.9", []),
    ("overactive_bladder", "Overactive Bladder", "ROUTINE", "N32.81", []),
    ("stress_incontinence", "Stress Urinary Incontinence", "ROUTINE", "N39.3", []),
    ("urethritis", "Urethritis", "URGENT", "N34.1", []),
    ("urethral_stricture", "Urethral Stricture", "URGENT", "N35.9", []),
    ("epididymo_orchitis", "Epididymo-Orchitis", "URGENT", "N45.3", []),
    ("hydrocele", "Hydrocele", "ROUTINE", "N43.3", []),
    ("balanitis", "Balanitis", "ROUTINE", "N48.1", []),
    ("erectile_dysfunction", "Erectile Dysfunction", "ROUTINE", "N52.9", []),
    ("menorrhagia", "Menorrhagia", "URGENT", "N92.0", []),
    ("amenorrhea", "Amenorrhea", "ROUTINE", "N91.2", []),
    ("dysmenorrhea", "Dysmenorrhea", "ROUTINE", "N94.6", []),
    ("ovarian_cyst", "Ovarian Cyst", "ROUTINE", "N83.20", []),
    ("adenomyosis", "Adenomyosis", "ROUTINE", "N80.0", []),
    ("cervicitis", "Cervicitis", "URGENT", "N72", []),
    ("mastitis", "Mastitis", "URGENT", "N61.0", []),
    ("breast_abscess", "Breast Abscess", "URGENT", "N61.1", []),
    ("fibrocystic_breast", "Fibrocystic Breast Changes", "ROUTINE", "N60.19", []),
    ("menopause", "Menopausal Syndrome", "ROUTINE", "N95.1", []),
])

# --- Perinatal/congenital (P00–Q99) ----------------------------------------------------------
PERINATAL_CONGENITAL = _mk("con", "congenital", [
    ("neonatal_sepsis", "Neonatal Sepsis", "CRITICAL", "P36.9", []),
    ("respiratory_distress_newborn", "Neonatal Respiratory Distress Syndrome", "CRITICAL", "P22.0", ["rds"]),
    ("meconium_aspiration", "Meconium Aspiration Syndrome", "CRITICAL", "P24.01", []),
    ("hypoxic_ischemic_encephalopathy", "Hypoxic-Ischemic Encephalopathy", "CRITICAL", "P91.60", ["hie"]),
    ("kernicterus", "Kernicterus", "CRITICAL", "P57.9", []),
    ("patent_ductus_arteriosus", "Patent Ductus Arteriosus", "URGENT", "Q25.0", ["pda"]),
    ("transposition_great_arteries", "Transposition of the Great Arteries", "CRITICAL", "Q20.3", []),
    ("hypoplastic_left_heart", "Hypoplastic Left Heart Syndrome", "CRITICAL", "Q23.4", []),
    ("truncus_arteriosus", "Truncus Arteriosus", "CRITICAL", "Q20.0", []),
    ("pyloric_stenosis_con", "Congenital Pyloric Stenosis", "URGENT", "Q40.0", []),
    ("duodenal_atresia", "Duodenal Atresia", "CRITICAL", "Q41.0", []),
    ("imperforate_anus", "Imperforate Anus", "URGENT", "Q42.3", []),
    ("gastroschisis", "Gastroschisis", "CRITICAL", "Q79.3", []),
    ("omphalocele", "Omphalocele", "CRITICAL", "Q79.2", []),
    ("diaphragmatic_hernia", "Congenital Diaphragmatic Hernia", "CRITICAL", "Q79.0", []),
    ("cleft_palate", "Cleft Palate", "ROUTINE", "Q35.9", []),
    ("club_foot", "Congenital Talipes Equinovarus", "ROUTINE", "Q66.0", ["club foot"]),
    ("developmental_hip_dysplasia", "Developmental Dysplasia of the Hip", "URGENT", "Q65.9", ["ddh"]),
    ("trisomy_18", "Trisomy 18", "URGENT", "Q91.3", ["edwards syndrome"]),
    ("trisomy_13", "Trisomy 13", "URGENT", "Q91.7", ["patau syndrome"]),
    ("fragile_x", "Fragile X Syndrome", "ROUTINE", "Q99.2", []),
    ("prader_willi", "Prader-Willi Syndrome", "ROUTINE", "Q87.11", []),
    ("noonan", "Noonan Syndrome", "ROUTINE", "Q87.19", []),
    ("williams_syndrome", "Williams Syndrome", "ROUTINE", "Q93.82", []),
])

# --- Symptoms/signs + injury/poisoning (R00–T88) ---------------------------------------------
SYMPTOMS_INJURY = _mk("sym", "general", [
    ("syncope", "Syncope", "URGENT", "R55", []),
    ("chest_pain_unspecified", "Chest Pain, Unspecified", "URGENT", "R07.9", []),
    ("dyspnea_symptom", "Dyspnea", "URGENT", "R06.00", []),
    ("hemoptysis", "Hemoptysis", "URGENT", "R04.2", []),
    ("hematuria", "Hematuria", "URGENT", "R31.9", []),
    ("jaundice_symptom", "Jaundice", "URGENT", "R17", []),
    ("ascites", "Ascites", "URGENT", "R18.8", []),
    ("lymphadenopathy", "Lymphadenopathy", "URGENT", "R59.9", []),
    ("splenomegaly", "Splenomegaly", "URGENT", "R16.1", []),
    ("weight_loss_symptom", "Unintentional Weight Loss", "URGENT", "R63.4", []),
    ("fever_unknown_origin", "Fever of Unknown Origin", "URGENT", "R50.9", ["fuo"]),
    ("altered_mental_status", "Altered Mental Status", "CRITICAL", "R41.82", ["ams"]),
    ("seizure_symptom", "Seizure", "URGENT", "R56.9", []),
    ("shock_unspecified", "Shock, Unspecified", "CRITICAL", "R57.9", []),
    ("cardiac_arrest", "Cardiac Arrest", "CRITICAL", "I46.9", []),
    ("respiratory_arrest", "Respiratory Arrest", "CRITICAL", "R09.2", []),
    ("anaphylactic_shock", "Anaphylactic Shock", "CRITICAL", "T78.2XXA", []),
    ("distributive_shock", "Distributive Shock", "CRITICAL", "R57.8", []),
    ("hypovolemic_shock", "Hypovolemic Shock", "CRITICAL", "R57.1", []),
    ("burns", "Thermal Burn", "CRITICAL", "T30.0", []),
    ("smoke_inhalation", "Smoke Inhalation Injury", "CRITICAL", "T59.811A", []),
    ("near_drowning", "Submersion Injury", "CRITICAL", "T75.1XXA", []),
    ("snakebite", "Venomous Snakebite", "CRITICAL", "T63.001A", []),
    ("crush_injury", "Crush Injury", "CRITICAL", "T14.8", []),
    ("blast_injury", "Blast Injury", "CRITICAL", "T70.8", []),
    ("transfusion_reaction", "Acute Transfusion Reaction", "CRITICAL", "T80.919A", []),
    ("adverse_drug_reaction", "Adverse Drug Reaction", "URGENT", "T88.7XXA", ["adr"]),
    ("contrast_reaction", "Contrast Media Reaction", "URGENT", "T88.59XA", []),
    ("dehydration_symptom", "Dehydration", "URGENT", "E86.0", []),
])


ALL_EXPANSION_GROUPS = [
    INFECTIOUS, NEOPLASMS, HEME_IMMUNE, ENDO_METAB, PSYCH, NEURO, EYE, EAR,
    CIRC, RESP, GI, DERM, MSK, GU, PERINATAL_CONGENITAL, SYMPTOMS_INJURY,
]
